
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "jerald.vit@gmail.com",
  "password": "test@12345"
}


#### Particular ID
GET http://localhost:3000/auth/1

####
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "praveen@gmail.com",
  "password": "test@12345"
}