
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "derrick@gmail.com",
  "password": "test@12345"
}


#### GET Particular ID
GET http://localhost:3000/auth/5

####
PATCH http://localhost:3000/auth/4
content-type: application/json

{
  "email": "praveen@gmail.com",
  "password": "test@12345"
}

#### Delete Particular ID
DELETE http://localhost:3000/auth/3