
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "derrick@gmail.com",
  "password": "test@12345"
}


#### GET Particular ID
GET http://localhost:3000/auth/5

#### GET All Users With Email
GET http://localhost:3000/auth?email=derrick@gmail.com

####
PATCH http://localhost:3000/auth/4
content-type: application/json

{
  "password": "praveen@gmail.com"
}

#### Delete Particular ID
DELETE http://localhost:3000/auth/5